name: Danger Workflow
on: [pull_request]
jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run Danger
        run: pnpx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
